#!/bin/bash

ln -s $HOME/dotfiles/bash_profile $HOME/.bash_profile
ln -s $HOME/dotfiles/gitconfig    $HOME/.gitconfig
ln -s $HOME/dotfiles/gitignore    $HOME/.gitignore
ln -s $HOME/dotfiles/vimrc        $HOME/.vimrc
