#!/bin/bash

ln -sf $HOME/dotfiles/gitconfig $HOME/.gitconfig
ln -sf $HOME/dotfiles/bashrc    $HOME/.bashrc
ln -sf $HOME/dotfiles/vimrc     $HOME/.vimrc
ln -sf $HOME/dotfiles/hushlogin $HOME/.hushlogin
