#!/bin/bash

if [ -e $HOME/.secrets/ghq.private ]; then
  aws s3 cp $HOME/.secrets/ghq.private s3://dtyler.secrets/ghq.private
fi

if [ -e $HOME/.secrets/profile.pvt ]; then
  aws s3 cp $HOME/.secrets/profile.pvt s3://dtyler.secrets/profile.pvt
fi

if [ -e $HOME/.cache/hist.tsv ]; then
  # clone to local
  aws s3 cp s3://dtyler.secrets/histcache.tsv $HOME/.cache/remote.tsv

  # concat
  cat $HOME/.cache/remote.tsv $HOME/.cache/hist.tsv > $HOME/.cache/temp.tsv
  sort -k 3 $HOME/.cache/temp.tsv | uniq > $HOME/.cache/temp2.tsv

  # sync
  aws s3 cp $HOME/.cache/temp.tsv s3://dtyler.secrets/histcache.tsv

  # cleanup
  rm $HOME/.cache/remote.tsv
  rm $HOME/.cache/temp.tsv
  mv $HOME/.cache/temp2.tsv $HOME/.cache/hist.tsv
fi
