modmap:
  - name: SandS
    remap:
      KEY_SPACE:
        held: KEY_LEFTSHIFT
        alone: KEY_SPACE
  - name: EiKana
    remap:
      KEY_LEFTCTRL:
        held: KEY_LEFTCTRL
        alone: KEY_MUHENKAN
      KEY_RIGHTCTRL:
        held: KEY_RIGHTCTRL
        alone: KEY_HENKAN
