alias ls='ls --color -F'
alias ll='ls -alh'
alias vi='nvim'
alias vim='nvim'
alias g='git'
alias s='ssh $(grep -iE "^host[[:space:]]+[^*]" ~/.ssh/config | fzf | awk "{print \$2}")'
alias gc='g co `g b | fzf | sed -e "s/\* //g" | awk "{print \$1}"`'
alias gb='g b | fzf | xargs git branch -d'
alias gr='ghq-cd-fzf'
alias gf='g rbi `fzf-rebase`'
alias de='docker exec -it $(docker ps | fzf | cut -d " " -f 1) /bin/bash'
alias ds='docker exec -it $(docker ps | fzf | cut -d " " -f 1) /bin/sh'
alias ap='export AWS_DEFAULT_PROFILE=$(grep -iE "^[]+[^*]" ~/.aws/credentials | tr -d [| tr -d ] | fzf)'
